Pull request for code review
luis-novoa/enumerable_ruby pull request #4
Opened 2019-12-09 22:19 UTC by luis-novoa

2019-12-09 22:36 UTC, suretrust requested changes
Hi @luis-novoa and @RoodzFernando,

### Great job thus far! :raised_hands: Just a few suggestions to wrap this up.

- [ ] Please see my comments on your code.

- [ ] `[Optional]` Your tests are not covering a lot of cases, remember how many test cases were reviewed to merged the PR of the enumerable methods? Let's add some more test cases to cover a good range of cases.

**Kindly submit for another code review once these issues have been fixed.** _Happy coding!_ :tada:

2019-12-09 22:36 UTC, suretrust commented on .rspec
> +--require spec_helper
You could add the `--format documentation` flag to make your tests more readable.

2019-12-09 22:36 UTC, suretrust commented on spec/enumerable_spec.rb
> +    let(:new_array) { [] }
Instead of redefining this inside every describe block, let's make them global variables.

2019-12-09 22:36 UTC, suretrust commented on spec/enumerable_spec.rb
> +
Kindly change this to `require_relative`. It is Ruby convention to use require_relative within a directory.

2019-12-09 22:36 UTC, suretrust commented on spec/enumerable_spec.rb
> +
`require_relative '../enumerable_methods'`

2019-12-10 16:35 UTC, stratospherique requested changes
### Impressive Work @luis-novoa :clap: However, additional tests needs to be added in order for us to approve the project. check :arrow_down: 

- **[REQUIRED]** Specs should cover positive and negative scenarios ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/commonsense.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/)) 
- Example for **my_all?**: there is a spec for correct usage of method \[e.g. when passing a block or when you have literals, classes, regex exp as arguments`\] and also there is spec for wrong usage of method. :gear: 

### That's it :relaxed: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2019-12-10 18:17 UTC, stratospherique approved these changes
### Great work implementing the suggested changes :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

2019-12-10 19:40 UTC, merged